mountain/urls.py
from django.contrib import admin
from django.urls import path,include
from  . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mountain/',include('website.urls')),
        re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),


    #パスワードリセット
    path('password_reset_form/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html', from_email='EMAIL_HOST_USER'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_mail_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirmation.html'), name='password_reset_confirm'),
    path('accounts/password_reset_finish/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_finish.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf import settings
from django.urls import path
from .views import HomeView,MountainListView,MountainDetailView,ThemeListView,ThemeDetail,Contact,ContactSuccess,UserLoginView,RegistView,RegistSuccess,UserLogoutView,activate_user,edit_theme,delete_theme
from django.contrib.auth import views as auth_views
app_name = 'website'

EMAIL_HOST_USER = getattr(settings, "EMAIL_HOST_USER", None)

urlpatterns = [
    path('home/',HomeView.as_view(),name="home"),
    path('mountain_list/',MountainListView.as_view(),name="mountain_list"),
    path('mountain_detail/<int:pk>',MountainDetailView.as_view(),name="mountain_detail"),
    path('theme_list/',ThemeListView.as_view(),name="theme_list"),
    path('theme_detail/<int:theme_id>',ThemeDetail.as_view(),name="theme_detail"),
    path('contact/',Contact.as_view(),name="contact"),
    path('contact_success/',ContactSuccess.as_view(),name="contact_success"),
    path('user_login/', UserLoginView.as_view(), name="user_login"),
    path('user_logout/', UserLogoutView.as_view(), name="user_logout"),
    path('regist/', RegistView.as_view(), name="regist"),
    path('activate_user/<uuid:token>',activate_user,name="activate_user"),
    path('regist_success/', RegistSuccess.as_view(), name="regist_success"),
    path('edit_theme/<int:id>', edit_theme, name="edit_theme"),
    path('delete_theme/<int:id>', delete_theme, name="delete_theme"),
    
    
]

templates/activate_user.html
{% extends 'base.html' %}
{% block content %}
    ユーザを有効化しました
    <a href="{% url 'website:home' %}">ホームへ</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
   {% load static %}
   <meta charset="utf-8">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
   <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
   <title>長野の名峰</title>
   <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
   <script src="https://code.jquery.com/jquery-3.3.1.js"></script>


   <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
   <div class="wrapper">
      <!-- navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark py-3">
         <div class="container">
            <h2 class="pt-1 "><a class="text-white header" href="{% url 'website:home' %}">長野の名峰</a></h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
               aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
               {% if user.is_authenticated %}
               <p class="text-white mx-4 mt-2 justify-content-center">{{user.username}}さん,こんにちは</p>
               {% endif %}
               <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                     <a class="nav-link text-white" href="{% url 'website:home'%}">ホーム</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-white" href="{% url 'website:mountain_list'%}">山の一覧</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-white" href="{% url 'website:theme_list'%}">掲示板</a>
                  </li>
                  <li class="nav-item text-white">
                     <a class="nav-link text-white" href="{% url 'website:contact'%}">お問い合わせ</a>
                  </li>

                  {% if user.is_authenticated %}
                  <a href="{% url 'website:user_logout' %}"><button class="btn btn-secondary ms-2">ログアウト</button></a>
                  {% else %}
                  <li class="nav-item text-white">
                     <a class="nav-link text-white" href="{% url 'website:regist'%}">ユーザ登録</a>
                  </li>
               </ul>
               {% comment %} ↑のul片方だけボタンが入っている {% endcomment %}
               <a href="{% url 'website:user_login' %}"><button class="btn btn-primary ms-2">ログイン</button></a>
               {% endif %}
            </div>
         </div>
      </nav>
      {% comment %} {% if user.is_authenticated  %}
      <p class="text-white">{{user.username}}</p>
      {% endif %} {% endcomment %}
      {% block content %}{% endblock %}
      <footer id="footer">
         <div class="footer-top">
            <div class="container">
               <div class="row">
                  <div class="col-md-4">
                     <h2 class="text-white">長野の名峰</h2>
                  </div> 
                  <div class="col-md-2">
                     <ul class="list-unstyled">
                        <li><a href="{% url 'website:home'%}">ホーム</a></li>
                        <li><a href="{% url 'website:mountain_list'%}">山の一覧</a></li>
                        <li><a href="{% url 'website:theme_list'%}">掲示板</a></li>
                        <li><a href="{% url 'website:contact'%}">お問い合わせ</a></li>
                        <li><a href="{% url 'website:regist'%}">ユーザ登録</a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </footer>
   </div>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous">
   </script>
   <script type="text/javascript" src="{% static 'footerFixed.js' %}"></script>
   </script>
</body>

</html>

</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section id="contact" class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto text-center">
                <h1>お問い合わせ</h1>
                <p>
                    以下フォームよりお気軽にお問い合わせください。<br>
                    お問い合わせ内容の確認後、ご連絡させていただきます。
                </p>
            </div>
        </div>
        <form method="POST" class="row g-3 justify-content-center">
            {% csrf_token %}
            <div class="col-md-5">
                    {{form.name}}
            </div>
            <div class="col-md-5">
                    {{form.email}}
            </div>
            <div class="col-md-10">
                    {{form.message}}
            </div>
            <div class="col-md-10">
                <input type="submit" value="送信する" class="btn btn-primary">
            </div>
        </form>
    </div>
</section>

{% endblock %}

templates/contact_success.html
{% extends 'base.html' %}
{% block content %}
<p>お問い合わせいただきありがとうございます。</p>
<p>近日中にご連絡いたしますので、恐れ入りますが、しばらくお待ちください</p>
<a href="{% url 'website:home'%}">トップページに戻る</a>
{% endblock %}

templates/delete_theme.html
{% extends 'base.html' %}
{% block content %}
    <h3>削除画面</h3>
    <form method="POST">
        {% csrf_token %}
        {{edit_theme_form.as_p}}
        <input type="submit" value="削除する">
    </form>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="hero vh-100 d-flex align-items-center" id="home">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 mx-auto text-center">
                <h1 class="display-4 text-white"></h1>
                <h5 class="my-3 text-white">このサイトでは、長野の雄大な山々を紹介しています。<br>また、掲示板では山への情報を共有できます。</p>
                {% comment %} <a href="{% url 'website:user_login' %}" class="btn btn-primary me-2">ログイン</a>
                <a href="{% url 'website:theme_list'%}" class="btn btn-outline-light">掲示板へ</a> {% endcomment %}
            </div>
        </div>
    </div>
</div>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h1>Services</h1>
                <p>このサイトのサービスを紹介します</p>
            </div>
        </div>
        <div class="row g-4">
            <div class="col-lg-4 col-sm-12">
                <div class="service card-effect ">
                    <div class="iconbox">
                        <i class='bx bxs-photo-album'></i>
                    </div>
                    <h5 class="mt-4 mb-2">Pictures</h5>
                    <p>それぞれの山の特徴と素晴らしい写真によって長野の山々の魅力を再確認することができます。</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="service card-effect ">
                    <div class="iconbox">
                        <i class='bx bxs-log-in' ></i>
                    </div>
                    <h5 class="mt-4 mb-2">Services</h5>
                    <p>ユーザ登録することで、スレッドの立ち上げ、削除、スレッドへのコメント、各山へのコメントが可能になります。</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="service card-effect ">
                    <div class="iconbox">
                        <i class='bx bxs-message-square-detail'></i>
                    </div>
                    <h5 class="mt-4 mb-2">Comment</h5>
                    <p>コメント機能を活用して、ぜひいろいろな方と感想や思いを共有してみてください。</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="row">
    <div class="col-lg-6 col-img"></div>
    <div class="col-lg-6">
        <div class="container">
            <div class="row">
                <div class="col-md-10 pt-4 offset-md-1">
                    <h1>My thoughts</h1>
                    <p>日本は世界の中でも有数の名山があることで知られています。その中でも、長野県には、八ヶ岳や日本アルプスという日本有数の山々があります。これら長野の山々についての魅力を自分でも発信したいと思いこのサイトを作りました。</p>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock  %}

templates/mountain_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="row">
    <div class="col-lg-6 mountain-img">
        <img src="{{mountain.picture.url}}" alt="">
    </div>
    <div class="col-lg-6">
        <div class="container">
            <div class="row">
                <div class="col-md-10 pt-4 offset-md-1">
                    <h1>{{mountain.name}}</h1>
                    <p>{{mountain.text}}</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% for mcomment in mountain_comment %}
    <div class="col-8 offset-1">
        <p>名前:{{ mcomment.user }}　{{mcomment.create_at}}</p>
        <p>{{ mcomment.comment | linebreaks }}</p>
    </div>
    <div class="col-10 offset-1">
        <hr>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <form method="POST" class="col-10 offset-1 py-5">
        {% csrf_token %}
        <p class="py-1">{{form.comment}}</p>
        <input type="submit" value="投稿する">
    </form>
    {% endif %}
</section>
{% endblock content %}

templates/mountain_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h2>長野の名峰</h2>
<form action="{% url 'website:mountain_list' %}" method="get">
    <p>名前で検索 <input type="text" name="mountain_name" ></p>
    <p><input type="submit" value="検索する"></p>
</form>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>写真</th>
            <th>名前</th>
            <th>説明</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td><a href="{% url 'website:mountain_detail' pk=object.id %}"><img class="m_picture" src="{{object.picture.url}}"></a></td>
            <td><a href="{% url 'website:mountain_detail' pk=object.id %}">{{object.name}}</a></td>
            <td><p>{{object.text | truncatechars:100}}</p></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/password_reset.html
{% extends "base.html" %}
{% block content %}
<h2>パスワードリセット</h2>
<p>ユーザー登録が済んでいる方のみご利用ください</p>
<form method="post" style="padding-left:20px;">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-secondary ">パスワードをリセット</button>
</form>
{% endblock %}

templates/password_reset_finish.html
{% extends "base.html" %}
{% block content %}
<p>パスワードが変更されました。</p>
<p><a href="{% url 'website:user_login' %}">ログイン画面へ</a></p>
{% endblock %}

templates/regist.html
{% extends 'base.html' %}
{% block content %}
<section class="login-box">
    <div class="py-5">
        <div class="row g-3 justify-content-center ">
            <div class="col-md-8 mx-auto text-center">
                <h1>新規登録</h1>
            </div>
            <form method="POST" class="row g-3 justify-content-center ">
                {% csrf_token %}
                <div class="col-md-5 py-4">
                    {{form.as_p}}
                    ※パスワードは8文字以上かつ一般的でない文字列にしてください
                    <input type="submit" value="登録する" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/regist_success.html
{% extends 'base.html' %}
{% block content %}
メールにURLを送信しました。
ご確認ください。
<a href="{% url 'website:home' %}">ホームへ</a>
{% endblock %}

templates/theme_detail.html
{% extends 'base.html' %}
{% block content %}
<h2 class="text-right">{{theme.title}}</h2>
<div class="col-10 offset-1">
    <p class="text-right">作成ユーザー:{{theme.user}}</p>
    {% for comment in comments %}
        <p>{{forloop.counter}} {{ comment.user }} {{comment.create_at}}</p>
        <p>{{comment.comment}}</p>
        <hr>
    {% endfor %}
    
    <form method="POST">
        {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="投稿する">
    </form>
</div>
{% endblock content %}

templates/user_login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% for message in messages %}
<div {% if message.tags%}class="{{message.tags}}" {% endif %}>
    {{ message }}
</div>
{% endfor %}
<section class="login-box">
    <div class="py-5">
        <div class="row g-3 justify-content-center">
            <div class="col-md-8 mx-auto text-center">
                <h1>ログイン</h1>
            </div>
            <form method="POST" class="row g-3 justify-content-center">
                {% csrf_token %}
                <div class="col-md-5 py-4">
                    {{form.as_p}}
                    <input type="submit" value="ログイン" class="btn btn-primary"><br>
                    <a href="{% url 'website:regist' %}">会員登録がお済みでない方はこちら</a><br>
                    <a href="{% url 'password_reset' %}">パスワードを忘れた方はこちら</a>
                </div>
            </form>
            {% comment %} <p class="text-center">or</p>
            <hr> {% endcomment %}

            {% comment %} <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-2 col-sm-11">
                        <button class="btn btn-primary mt-2"> <i class='bx bxl-google'></i>FaceBookでログイン</button>
                        <button class="btn btn-primary mt-2"> <i class='bx bxl-google'></i>FaceBookでログイン</button>
                        <button class="btn btn-primary mt-2"> <i class='bx bxl-google'></i>FaceBookでログイン</button>
                    </div>
                </div>
            </div> {% endcomment %}
        </div>
</section>
{% endblock %}